### PR TITLE
Improve ability to re-emit failed events for ChattermillResponse agent

### PR DESCRIPTION
**Pull request by monsha**
- [x] Added source event id to emitted events payload
- [x] Added source event link to failed event slack notification

### Trello
https://trello.com/c/I3JBkRmX/428-improve-ability-to-re-emit-failed-events-for-chattermillresponse-agent

### CODE REVIEW

**Review by duboff — APPROVED** [review]
LGTM

**Comment by duboff** [comment]
@monsha can you please send PRs for review to @rrodrigu3z first, or if he has already reviewed ask him to leave a 👍 here so I know it's been looked at by someone else.

**Comment by monsha** [comment]
Ok @duboff, get it!

**Comment by rrodrigu3z** [comment]
@duboff My fault, I gave feedback to @monsha directly when we were at the office. I should've added a 👍 here later, will do it next time.

**Pull request merged**
