### PR TITLE
Chattermill Response Agent

### PR DESCRIPTION
**Pull request by rrodrigu3z**
- [x] Add new agent
- [x] Add specs for new Chattermill Agent
- [x] Update ace editor (solves jump/scroll issue with onClick/focus events)
- [x] Add :json support to `form_configurable` & update specs

### Main Options

screen shot 2017-03-01 at 12 58 49 pm

### JSON options With ace editor

screen shot 2017-03-01 at 12 59 08 pm

### Extra fields
Allows to build additional fields for the Response, e.g: `{ approved: true }`

screen shot 2017-03-01 at 12 59 19 pm

### CODE REVIEW

**Comment by rrodrigu3z** [comment]
@duboff I went for an Ace editor for `segments` and `user_meta`.  I'm not sure if that's the best option for us because I don't know if the huginn users will have knowledge of JSON.

I've included some screenshots, please, let me know what do you think. I could also deploy the branch to our huginn server I suppose.

**Comment by duboff** [comment]
@rrodrigu3z I think we don't need the protocol / domain options. They should just point to correct places for production / development.

I think Emit Events option should be set to true by default (so we can hook up Slack notifications for errors).

Other than that, looks pretty good.

**Comment by rrodrigu3z** [comment]
@duboff should we use an option to select "Environment" (production. staging, development) ? or just point to the right place based on `Rails.env`?

**Comment by duboff** [comment]
Yes, just use the rails one. The fewer options the better

**Comment by rrodrigu3z** [comment]
Ok, Thanks.

**Comment by rrodrigu3z** [comment]
Added 2 env vars:
`SLACK_WEBHOOK_URL`
`SLACK_CHANNEL=#bots`

**Comment by rrodrigu3z** [comment]
## Slack notification screenshot

screen shot 2017-03-06 at 7 59 23 pm

**Comment by duboff** [comment]
Great work, a couple of suggestions (let me know if any of them seem like a bad idea):

create agent - huginn 2017-03-08 10-46-37
create agent - huginn 2017-03-08 10-45-23

**Comment by rrodrigu3z** [comment]
Ok, the `Schedule` field can be disabled, the built-in way to do it will print a message instead of the field.  `Keep events` will need some tweaks in the view, I think it should not be a problem.

So, for `auth_token` field we will need and ENV var.

**Comment by duboff** [comment]
OK, if it's not super straightforward, le's leave those fields.

And yes re auth_token

Also, re Slack agent, any chance we can include the source agent name?

**Comment by rrodrigu3z** [comment]
It turns out that the form section for main attributes is not easily customizable (not without dealing with partials, controllers and coffeescript).  
I couldn't find an easy way to override the default value for for `Propagate Immediately` option. What I think we can do is override it for all new agents, but I don't know if that is a good idea.

## New Screenshots

screen shot 2017-03-08 at 5 56 13 pm

screen shot 2017-03-08 at 5 56 55 pm

screen shot 2017-03-08 at 6 05 52 pm

**Comment by duboff** [comment]
This looks great. Please deploy

**Review by duboff — APPROVED** [review]

**Pull request merged**
