### PR TITLE
Use Sidekiq to process jobs

### PR DESCRIPTION
**Pull request by rrodrigu3z**
Tested with basic Sidekiq setup and looks like everything is working.

### TODO:

- [x] Add Redis config
- [x] Add Sidekiq config file and/or number of process & workers
- [x] Setup works with dokku? // (works with foreman locally) // Works on DO
- [x] Sidekiq UI on /sidekiq

### Notes:

Run with chattermill configs:
`foreman start -f deployment/chattermill/Procfile -d .`

Also, `foreman start` will use Sidekiq too, but web process uses Webrick.

### How to install on DO
We need to install Redis on DO droplet and scale dokku processes to boot up sidekiq and scheduler

```
----- Redis -----
dokku plugin:install https://github.com/dokku/dokku-redis.git redis
dokku redis:create huginn
dokku redis:link huginn huginn
-------------------------------

# Change Profile
dokku config:set PROCFILE_PATH=deployment/chattermill/Procfile

# Scale workers
dokku ps:scale huginn schedule=1 sidekiq=1
```

### CODE REVIEW

**Comment by rrodrigu3z** [comment]
@duboff can we boot up a new temporary DO droplet for testing this on Dokku?, check memory usage, etc? I don't want to scale current droplet because a testing/staging env.

**Comment by duboff** [comment]
@rrodrigu3z yes of course!

**Comment by rrodrigu3z** [comment]
@dubff I think it's working fine on DO. 

`Web + Scheduler + 2 Sidekiq processes` uses about 900MB of Memory. Of course that will be a little higher on production when running real jobs. But we're getting higher concurrency. Also, we can try with only 1 Sidekiq process, then scale.

**Comment by rrodrigu3z** [comment]
If you want to look at it, you can try it at: 

* http://huginn-staging.chattermill.xyz/
* http://huginn-staging.chattermill.xyz/sidekiq

Note: You will need to add `46.101.2.142 huginn-staging.chattermill.xyz` to your `/etc/hosts`

**Comment by duboff** [comment]
LGTM, pls deploy

**Comment by rrodrigu3z** [comment]
Redis installed on production and merged, I'll deploy it tomorrow morning to be able to monitor during my morning

**Pull request merged**
