### PR TITLE
S3Agent ergonomics

### PR DESCRIPTION
**Pull request by rrodrigu3z**
### Description
https://trello.com/c/fA5IqOkV/433-better-ergonomics-for-s3-huginn-agent

- [x] Add prefix option
- [x] Add suffix option
- [x] Add event type option
- [x] Update agent specs

### CODE REVIEW

**Comment by duboff** [comment]
Can we call the options Prefix and Suffix, without the `filter`? Otherwise good to go

**Comment by rrodrigu3z** [comment]
Updated.

### Screenshot

screen shot 2017-09-20 at 9 29 15 pm

**Comment by rrodrigu3z** [comment]
@duboff is this one approved?

**Review by duboff — APPROVED** [review]
Great work!

**Pull request merged**
