### PR TITLE
Monitoring tools

### PR DESCRIPTION
**Pull request by monsha**
Added pghero. 
Added bullet gem to look for N+1 queries and unused eager loading.

### Notes
Add the following to postgresql.conf:
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
pg_stat_statements.max = 10000
track_activity_query_size = 2048

Then restart PostgreSQL.

Schedule the task below to run every 5 minutes:
bundle exec rails pghero:capture_query_stats

### CODE REVIEW

**Comment by duboff** [comment]
Did you notice any n+1s in testing / running common tasks?

**Comment by monsha** [comment]
Not yet, only eager loading detected

**Review by OpakAlex — APPROVED** [review]

**Review by duboff — APPROVED** [review]
👍

**Comment by duboff** [comment]
@monsha this is good to deploy

**Pull request merged**
