### PR TITLE
Add support for dataset_id in ChattermillResponseAgent

### PR DESCRIPTION
**Pull request by rrodrigu3z**
API Related PR: https://github.com/chattermill/cm-backend/pull/618

### CODE REVIEW

**Comment by rrodrigu3z** [comment]
@duboff Using `dataset_id` will prevent `data_type` related validations to run, e.g. Using `dataset_id=x` instead of `kind=nps` will skip checks on score presence (on Huginn side).

**Comment by duboff** [comment]
Great this looks good to go, is there a way to make this new field mandatory for all newly created agents?

**Comment by rrodrigu3z** [comment]
@duboff yeah I think so. Let me try.

**Comment by rrodrigu3z** [comment]
@duboff Updated. It checks presence if agent is `new_record?`. I think it can work.

Also, I think we can improve usability by making it a dropdown, huginn has support for that. We can fetch organization's datasets using our API. `S3Agent`does it for buckets. (this can be another PR)

**Comment by duboff** [comment]
Yes, sounds like a great idea but we can avoid it for now.

**Review by duboff — APPROVED** [review]
👍

**Pull request merged**
